/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.polysfactory.facerecognition.jni;

import com.opencv.jni.image_pool;// import the image_pool interface for playing nice with android-opencv

public class BarBar {
  private long swigCPtr;
  protected boolean swigCMemOwn;
  public BarBar(long cPtr, boolean cMemoryOwn) {
	swigCMemOwn = cMemoryOwn;
	swigCPtr = cPtr;
  }
  public static long getCPtr(BarBar obj) {
	return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      foobarJNI.delete_BarBar(swigCPtr);
    }
    swigCPtr = 0;
  }

  public BarBar() {
    this(foobarJNI.new_BarBar(), true);
  }

  public void recognizeFace(int idx, image_pool pool) {
    foobarJNI.BarBar_recognizeFace(swigCPtr, this, idx, image_pool.getCPtr(pool), pool);
  }

}
