/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.polysfactory.facerecognition.jni;

import com.opencv.jni.image_pool;// import the image_pool interface for playing nice with android-opencv

/** FooBar - template
*/
public class FooBarStruct {
  private long swigCPtr;
  protected boolean swigCMemOwn;
  public FooBarStruct(long cPtr, boolean cMemoryOwn) {
	swigCMemOwn = cMemoryOwn;
	swigCPtr = cPtr;
  }
  public static long getCPtr(FooBarStruct obj) {
	return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      foobarJNI.delete_FooBarStruct(swigCPtr);
    }
    swigCPtr = 0;
  }

  public int pool_image_count(image_pool pool) {
    return foobarJNI.FooBarStruct_pool_image_count(swigCPtr, this, image_pool.getCPtr(pool), pool);
  }

  public FooBarStruct() {
    this(foobarJNI.new_FooBarStruct(), true);
  }

}
