/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.polysfactory.facerecognition.jni;

import com.opencv.jni.*; //import the android-opencv jni wrappers

class foobarJNI {

	static {
		try {
			//load the cvcamera library, make sure that libcvcamera.so is in your <project>/libs/armeabi directory
			//so that android sdk automatically installs it along with the app.
			
			//the android-opencv lib must be loaded first inorder for the cvcamera
			//lib to be found
			//check the apk generated, by opening it in an archive manager, to verify that
			//both these libraries are present
			System.loadLibrary("android-opencv");
			System.loadLibrary("TestBar");
		} catch (UnsatisfiedLinkError e) {
			//badness
			throw e;
		}
	}


  public final static native int FooBarStruct_pool_image_count(long jarg1, FooBarStruct jarg1_, long jarg2, image_pool jarg2_);
  public final static native long new_FooBarStruct();
  public final static native void delete_FooBarStruct(long jarg1);
  public final static native long new_BarBar();
  public final static native void BarBar_recognizeFace(long jarg1, BarBar jarg1_, int jarg2, long jarg3, image_pool jarg3_);
  public final static native void delete_BarBar(long jarg1);
}
